# 成本函数

$$J(w,b) = \frac{1}{2m} \sum\limits_{i = 0}^{m-1} (f_{w,b}(x^{(i)}) - y^{(i)})^2 \tag{1}$$

$$f_{w,b}(x^{(i)}) = wx^{(i)} +b \tag{2}$$

先考虑单变量x，视b为标量

In [111]:
import numpy as np

In [112]:
x_train = np.array([100.0, 120.0])
y_train = np.array([3314.0, 3976.8])
print(f"x_train={x_train}, y_train={y_train}")

x_train=[100. 120.], y_train=[3314.  3976.8]


In [113]:
def computer_modle_output(x,w,b):
    m = x_train.shape[0] #训练集案例个数
    f_wb = np.zeros(m)
    for i in range(m):
        f_wb[i] = w * x[i] + b
    return f_wb



In [114]:
def computer_cost_function(x, y, w, b):
    m = x_train.shape[0]
    f_wb = computer_modle_output(x,w,b)
    j_wb = 0.
    for i in range(m):
        j_wb += (f_wb[i] - y[i]) ** 2
    j_wb = j_wb / (2* m)
    return j_wb


In [115]:
w = 100
b = 50
tmp = computer_cost_function(x_train, y_train, w, b)
print(tmp)
computer_modle_output(x_train, w, b)


27637563.56


array([10050., 12050.])

In [116]:
w = 40
b = 50
tmp2 = computer_cost_function(x_train, y_train, w, b)
print(tmp2)
computer_modle_output(x_train, w, b)

326043.55999999994


array([4050., 4850.])

In [117]:
w = 33
b = 50
tmp1 = computer_cost_function(x_train, y_train, w, b)
print(tmp1)
computer_modle_output(x_train, w, b)

599.559999999997


array([3350., 4010.])

多测几组数据，易得成本越低，w取得一个比较合适的值线性回归更准确。